use super::*;

pub const ENTRIES: &[IndicatorMeta] = &[
    IndicatorMeta {
        id: "cross",
        display_name: "Cross",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES, P_B_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Any cross event",
        }],
        semantics: SEM_CLOSE_PAIR,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "cross",
    },
    IndicatorMeta {
        id: "crossdown",
        display_name: "Cross Down",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES, P_B_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Cross down event",
        }],
        semantics: SEM_CLOSE_PAIR,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "crossdown",
    },
    IndicatorMeta {
        id: "crossup",
        display_name: "Cross Up",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES, P_B_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Cross up event",
        }],
        semantics: SEM_CLOSE_PAIR,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "crossup",
    },
    IndicatorMeta {
        id: "enter",
        display_name: "Enter Channel",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_PRICE_SERIES, P_UPPER_SERIES, P_LOWER_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Enter channel event",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["close"],
            optional_fields: &["upper", "lower"],
            lookback_params: &[],
            default_lookback: Some(2),
            warmup_policy: "none",
        },
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "enter",
    },
    IndicatorMeta {
        id: "exit",
        display_name: "Exit Channel",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_PRICE_SERIES, P_UPPER_SERIES, P_LOWER_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Exit channel event",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["close"],
            optional_fields: &["upper", "lower"],
            lookback_params: &[],
            default_lookback: Some(2),
            warmup_policy: "none",
        },
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "exit",
    },
    IndicatorMeta {
        id: "falling",
        display_name: "Falling",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Falling event",
        }],
        semantics: SEM_CLOSE_NO_LOOKBACK,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "falling",
    },
    IndicatorMeta {
        id: "falling_pct",
        display_name: "Falling By Percent",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES, P_PCT_5],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Falling by percent event",
        }],
        semantics: SEM_CLOSE_NO_LOOKBACK,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "falling_pct",
    },
    IndicatorMeta {
        id: "in_channel",
        display_name: "In Channel",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_PRICE_SERIES, P_UPPER_SERIES, P_LOWER_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "In channel event",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["close"],
            optional_fields: &["upper", "lower"],
            lookback_params: &[],
            default_lookback: Some(1),
            warmup_policy: "none",
        },
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "in_channel",
    },
    IndicatorMeta {
        id: "out",
        display_name: "Out Of Channel",
        category: "event",
        aliases: &["out_channel"],
        param_aliases: &[],
        params: &[P_PRICE_SERIES, P_UPPER_SERIES, P_LOWER_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Out of channel event",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["close"],
            optional_fields: &["upper", "lower"],
            lookback_params: &[],
            default_lookback: Some(1),
            warmup_policy: "none",
        },
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "out",
    },
    IndicatorMeta {
        id: "rising",
        display_name: "Rising",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Rising event",
        }],
        semantics: SEM_CLOSE_NO_LOOKBACK,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "rising",
    },
    IndicatorMeta {
        id: "rising_pct",
        display_name: "Rising By Percent",
        category: "event",
        aliases: &[],
        param_aliases: &[],
        params: &[P_A_SERIES, P_PCT_5],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "signal",
            description: "Rising by percent event",
        }],
        semantics: SEM_CLOSE_NO_LOOKBACK,
        visual: VIS_SIGNAL_FLAG,
        runtime_binding: "rising_pct",
    },
];
