use super::*;

pub const ENTRIES: &[IndicatorMeta] = &[
    IndicatorMeta {
        id: "ao",
        display_name: "Awesome Oscillator",
        category: "momentum",
        aliases: &[],
        param_aliases: &[],
        params: &[P_FAST_PERIOD_5, P_SLOW_PERIOD_34],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "column",
            description: "AO value",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low"],
            optional_fields: &[],
            lookback_params: &["fast_period", "slow_period"],
            default_lookback: None,
            warmup_policy: "window",
        },
        visual: VIS_VOLUME_HIST,
        runtime_binding: "ao",
    },
    IndicatorMeta {
        id: "cci",
        display_name: "Commodity Channel Index",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_20],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "CCI value",
        }],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_OSC_LINE,
        runtime_binding: "cci",
    },
    IndicatorMeta {
        id: "cmo",
        display_name: "Chande Momentum Oscillator",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "CMO value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_OSC_LINE,
        runtime_binding: "cmo",
    },
    IndicatorMeta {
        id: "coppock",
        display_name: "Coppock Curve",
        category: "momentum",
        aliases: &[],
        param_aliases: &[],
        params: &[
            IndicatorParamMeta {
                name: "wma_period",
                kind: IndicatorParamKind::Integer,
                required: false,
                default: Some("10"),
                description: "WMA period",
                min: Some(1.0),
                max: None,
            },
            IndicatorParamMeta {
                name: "fast_roc",
                kind: IndicatorParamKind::Integer,
                required: false,
                default: Some("11"),
                description: "Fast ROC period",
                min: Some(1.0),
                max: None,
            },
            IndicatorParamMeta {
                name: "slow_roc",
                kind: IndicatorParamKind::Integer,
                required: false,
                default: Some("14"),
                description: "Slow ROC period",
                min: Some(1.0),
                max: None,
            },
        ],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "Coppock value",
        }],
        semantics: SEM_CLOSE_FAST_SLOW_SIGNAL,
        visual: VIS_OSC_LINE,
        runtime_binding: "coppock",
    },
    IndicatorMeta {
        id: "mfi",
        display_name: "Money Flow Index",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "MFI value",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low", "close", "volume"],
            optional_fields: &[],
            lookback_params: &["period"],
            default_lookback: None,
            warmup_policy: "window",
        },
        visual: VIS_OSC_LINE,
        runtime_binding: "mfi",
    },
    IndicatorMeta {
        id: "roc",
        display_name: "Rate of Change",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_12],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "ROC value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_PRICE_LINE,
        runtime_binding: "roc",
    },
    IndicatorMeta {
        id: "rsi",
        display_name: "Relative Strength Index",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "RSI value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_OSC_LINE,
        runtime_binding: "rsi",
    },
    IndicatorMeta {
        id: "stochastic",
        display_name: "Stochastic Oscillator",
        category: "momentum",
        aliases: &["stoch", "stochastic_kd", "stoch_k", "stoch_d"],
        param_aliases: &[],
        params: &[P_K_PERIOD_14, P_D_PERIOD_3, P_SMOOTH_1],
        outputs: &[
            IndicatorOutputMeta {
                name: "k",
                kind: "osc_main",
                description: "K line",
            },
            IndicatorOutputMeta {
                name: "d",
                kind: "osc_signal",
                description: "D line",
            },
        ],
        semantics: SEM_OHLC_STOCH,
        visual: VIS_STOCHASTIC,
        runtime_binding: "stochastic_kd",
    },
    IndicatorMeta {
        id: "vortex",
        display_name: "Vortex Indicator",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[
            IndicatorOutputMeta {
                name: "plus",
                kind: "line",
                description: "VI+",
            },
            IndicatorOutputMeta {
                name: "minus",
                kind: "line",
                description: "VI-",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_VORTEX,
        runtime_binding: "vortex",
    },
    IndicatorMeta {
        id: "williams_r",
        display_name: "Williams %R",
        category: "momentum",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "Williams %R value",
        }],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_OSC_LINE,
        runtime_binding: "williams_r",
    },
];
