use super::*;

pub const ENTRIES: &[IndicatorMeta] = &[
    IndicatorMeta {
        id: "adx",
        display_name: "Average Directional Index",
        category: "trend",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[
            IndicatorOutputMeta {
                name: "adx",
                kind: "line",
                description: "ADX value",
            },
            IndicatorOutputMeta {
                name: "plus_di",
                kind: "line",
                description: "Positive directional indicator",
            },
            IndicatorOutputMeta {
                name: "minus_di",
                kind: "line",
                description: "Negative directional indicator",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_ADX,
        runtime_binding: "adx",
    },
    IndicatorMeta {
        id: "elder_ray",
        display_name: "Elder Ray Index",
        category: "trend",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[IndicatorParamMeta {
            name: "period",
            kind: IndicatorParamKind::Integer,
            required: false,
            default: Some("13"),
            description: "EMA period",
            min: Some(1.0),
            max: None,
        }],
        outputs: &[
            IndicatorOutputMeta {
                name: "bull",
                kind: "histogram",
                description: "Bull power",
            },
            IndicatorOutputMeta {
                name: "bear",
                kind: "histogram",
                description: "Bear power",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_ELDER_RAY,
        runtime_binding: "elder_ray",
    },
    IndicatorMeta {
        id: "ema",
        display_name: "Exponential Moving Average",
        category: "trend",
        aliases: &["rolling_ema"],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_20, P_SOURCE_STR],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "EMA value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_PRICE_LINE,
        runtime_binding: "ema",
    },
    IndicatorMeta {
        id: "fisher",
        display_name: "Fisher Transform",
        category: "trend",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[IndicatorParamMeta {
            name: "period",
            kind: IndicatorParamKind::Integer,
            required: false,
            default: Some("9"),
            description: "Lookback period",
            min: Some(1.0),
            max: None,
        }],
        outputs: &[
            IndicatorOutputMeta {
                name: "fisher",
                kind: "line",
                description: "Fisher value",
            },
            IndicatorOutputMeta {
                name: "signal",
                kind: "signal",
                description: "Signal value",
            },
        ],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low"],
            optional_fields: &[],
            lookback_params: &["period"],
            default_lookback: None,
            warmup_policy: "window",
        },
        visual: VIS_FISHER,
        runtime_binding: "fisher",
    },
    IndicatorMeta {
        id: "hma",
        display_name: "Hull Moving Average",
        category: "trend",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "HMA value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_PRICE_LINE,
        runtime_binding: "hma",
    },
    IndicatorMeta {
        id: "ichimoku",
        display_name: "Ichimoku Cloud",
        category: "trend",
        aliases: &[],
        param_aliases: &[],
        params: &[P_TENKAN_9, P_KIJUN_26, P_SPAN_B_52, P_DISPLACEMENT_26],
        outputs: &[
            IndicatorOutputMeta {
                name: "tenkan_sen",
                kind: "line",
                description: "Tenkan-sen",
            },
            IndicatorOutputMeta {
                name: "kijun_sen",
                kind: "line",
                description: "Kijun-sen",
            },
            IndicatorOutputMeta {
                name: "senkou_span_a",
                kind: "line",
                description: "Senkou Span A",
            },
            IndicatorOutputMeta {
                name: "senkou_span_b",
                kind: "line",
                description: "Senkou Span B",
            },
            IndicatorOutputMeta {
                name: "chikou_span",
                kind: "line",
                description: "Chikou Span",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_ICHIMOKU,
        runtime_binding: "ichimoku",
    },
    IndicatorMeta {
        id: "macd",
        display_name: "Moving Average Convergence Divergence",
        category: "trend",
        aliases: &[],
        param_aliases: &[],
        params: &[P_FAST_PERIOD_12, P_SLOW_PERIOD_26, P_SIGNAL_PERIOD_9],
        outputs: &[
            IndicatorOutputMeta {
                name: "macd",
                kind: "line",
                description: "MACD line",
            },
            IndicatorOutputMeta {
                name: "signal",
                kind: "signal",
                description: "Signal line",
            },
            IndicatorOutputMeta {
                name: "histogram",
                kind: "histogram",
                description: "MACD histogram",
            },
        ],
        semantics: SEM_CLOSE_FAST_SLOW_SIGNAL,
        visual: VIS_MACD,
        runtime_binding: "macd",
    },
    IndicatorMeta {
        id: "psar",
        display_name: "Parabolic SAR",
        category: "trend",
        aliases: &[],
        param_aliases: &[],
        params: &[P_AF_START_002, P_AF_INCREMENT_002, P_AF_MAX_02],
        outputs: &[
            IndicatorOutputMeta {
                name: "sar",
                kind: "line",
                description: "SAR value",
            },
            IndicatorOutputMeta {
                name: "direction",
                kind: "signal",
                description: "Trend direction",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_PSAR,
        runtime_binding: "psar",
    },
    IndicatorMeta {
        id: "sma",
        display_name: "Simple Moving Average",
        category: "trend",
        aliases: &["rolling_mean", "mean"],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_20, P_SOURCE_STR],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "SMA value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_PRICE_LINE,
        runtime_binding: "sma",
    },
    IndicatorMeta {
        id: "supertrend",
        display_name: "Supertrend",
        category: "trend",
        aliases: &[],
        param_aliases: &[],
        params: &[P_PERIOD_12, P_MULTIPLIER_3],
        outputs: &[
            IndicatorOutputMeta {
                name: "supertrend",
                kind: "line",
                description: "Supertrend line",
            },
            IndicatorOutputMeta {
                name: "direction",
                kind: "signal",
                description: "Trend direction",
            },
        ],
        semantics: SEM_OHLC_PERIOD,
        visual: VIS_SUPERTREND,
        runtime_binding: "supertrend",
    },
    IndicatorMeta {
        id: "wma",
        display_name: "Weighted Moving Average",
        category: "trend",
        aliases: &["rolling_wma"],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_14, P_SOURCE_STR],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "line",
            description: "WMA value",
        }],
        semantics: SEM_CLOSE_PERIOD,
        visual: VIS_PRICE_LINE,
        runtime_binding: "wma",
    },
];
