use super::*;

pub const ENTRIES: &[IndicatorMeta] = &[
    IndicatorMeta {
        id: "cmf",
        display_name: "Chaikin Money Flow",
        category: "volume",
        aliases: &[],
        param_aliases: &[PARAM_ALIAS_LOOKBACK_PERIOD],
        params: &[P_PERIOD_20],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "volume",
            description: "CMF value",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low", "close", "volume"],
            optional_fields: &[],
            lookback_params: &["period"],
            default_lookback: None,
            warmup_policy: "window",
        },
        visual: VIS_VOLUME_LINE,
        runtime_binding: "cmf",
    },
    IndicatorMeta {
        id: "klinger_vf",
        display_name: "Klinger Volume Force",
        category: "volume",
        aliases: &["klinger"],
        param_aliases: &[],
        params: &[],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "volume",
            description: "Raw Klinger volume force",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low", "close", "volume"],
            optional_fields: &[],
            lookback_params: &[],
            default_lookback: Some(1),
            warmup_policy: "none",
        },
        visual: VIS_VOLUME_LINE,
        runtime_binding: "klinger_vf",
    },
    IndicatorMeta {
        id: "obv",
        display_name: "On Balance Volume",
        category: "volume",
        aliases: &[],
        param_aliases: &[],
        params: &[],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "volume",
            description: "OBV value",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["close", "volume"],
            optional_fields: &[],
            lookback_params: &[],
            default_lookback: Some(2),
            warmup_policy: "none",
        },
        visual: VIS_VOLUME_LINE,
        runtime_binding: "obv",
    },
    IndicatorMeta {
        id: "vwap",
        display_name: "Volume Weighted Average Price",
        category: "volume",
        aliases: &[],
        param_aliases: &[],
        params: &[],
        outputs: &[IndicatorOutputMeta {
            name: "result",
            kind: "volume",
            description: "VWAP value",
        }],
        semantics: IndicatorSemanticsMeta {
            required_fields: &["high", "low", "close", "volume"],
            optional_fields: &[],
            lookback_params: &[],
            default_lookback: Some(1),
            warmup_policy: "none",
        },
        visual: VIS_PRICE_LINE,
        runtime_binding: "vwap",
    },
];
